import {
  PatientOption,
  TherapistOption,
  TherapySession,
} from "./session-types";

export const patients: PatientOption[] = [
  {
    id: 1,
    name: "John Doe",
    patientId: "PT-1001",
  },
  {
    id: 2,
    name: "Sarah Wilson",
    patientId: "PT-1002",
  },
  {
    id: 3,
    name: "Michael Brown",
    patientId: "PT-1003",
  },
  {
    id: 4,
    name: "Emily Johnson",
    patientId: "PT-1004",
  },
  {
    id: 5,
    name: "David Smith",
    patientId: "PT-1005",
  },
  {
    id: 6,
    name: "Sophia Miller",
    patientId: "PT-1006",
  },
];

export const therapists: TherapistOption[] = [
  {
    id: 101,
    name: "Dr. Sarah Wilson",
    therapistId: "TH-1001",
  },
  {
    id: 102,
    name: "Dr. Michael Brown",
    therapistId: "TH-1002",
  },
  {
    id: 103,
    name: "Dr. Emily Johnson",
    therapistId: "TH-1003",
  },
  {
    id: 104,
    name: "Dr. David Smith",
    therapistId: "TH-1004",
  },
];

export const sessions: TherapySession[] = [
  {
    id: 1,
    patientId: 1,
    patientName: "John Doe",
    patientCode: "PT-1001",
    therapistId: 101,
    therapistName: "Dr. Sarah Wilson",
    therapistCode: "TH-1001",
    sessionDate: "2026-09-29T09:00:00",
    durationMinutes: 60,
    sessionType: "initial_assessment",
    status: "scheduled",
    mode: "in_person",
    paymentMethod: "cash",
    presentingConcerns: "Anxiety and sleep difficulties.",
    sessionGoals: "Initial assessment and treatment planning.",
    followUpRequired: true,
    createdAt: "2026-09-28T10:00:00",
    updatedAt: "2026-09-28T10:00:00",
  },
  {
    id: 2,
    patientId: 2,
    patientName: "Sarah Wilson",
    patientCode: "PT-1002",
    therapistId: 102,
    therapistName: "Dr. Michael Brown",
    therapistCode: "TH-1002",
    sessionDate: "2026-09-29T10:00:00",
    durationMinutes: 60,
    sessionType: "individual",
    status: "scheduled",
    mode: "telehealth",
    paymentMethod: "card",
    presentingConcerns: "Stress management.",
    sessionGoals: "Develop coping strategies.",
    followUpRequired: true,
    createdAt: "2026-09-28T10:00:00",
    updatedAt: "2026-09-28T10:00:00",
  },
  {
    id: 3,
    patientId: 3,
    patientName: "Michael Brown",
    patientCode: "PT-1003",
    therapistId: 103,
    therapistName: "Dr. Emily Johnson",
    therapistCode: "TH-1003",
    sessionDate: "2026-09-29T11:00:00",
    durationMinutes: 60,
    sessionType: "follow_up",
    status: "completed",
    mode: "in_person",
    paymentMethod: "cash",
    presentingConcerns: "Follow-up assessment.",
    sessionGoals: "Review progress.",
    followUpRequired: false,
    createdAt: "2026-09-28T10:00:00",
    updatedAt: "2026-09-29T12:00:00",
  },
  {
    id: 4,
    patientId: 4,
    patientName: "Emily Johnson",
    patientCode: "PT-1004",
    therapistId: 104,
    therapistName: "Dr. David Smith",
    therapistCode: "TH-1004",
    sessionDate: "2026-09-29T14:00:00",
    durationMinutes: 60,
    sessionType: "individual",
    status: "scheduled",
    mode: "in_person",
    paymentMethod: "online",
    presentingConcerns: "Relationship difficulties.",
    sessionGoals: "Individual therapy.",
    followUpRequired: true,
    createdAt: "2026-09-28T10:00:00",
    updatedAt: "2026-09-28T10:00:00",
  },
  {
    id: 5,
    patientId: 5,
    patientName: "David Smith",
    patientCode: "PT-1005",
    therapistId: 101,
    therapistName: "Dr. Sarah Wilson",
    therapistCode: "TH-1001",
    sessionDate: "2026-09-30T10:00:00",
    durationMinutes: 60,
    sessionType: "follow_up",
    status: "scheduled",
    mode: "in_person",
    paymentMethod: "bank_transfer",
    followUpRequired: true,
    createdAt: "2026-09-29T10:00:00",
    updatedAt: "2026-09-29T10:00:00",
  },
  {
    id: 6,
    patientId: 6,
    patientName: "Sophia Miller",
    patientCode: "PT-1006",
    therapistId: 102,
    therapistName: "Dr. Michael Brown",
    therapistCode: "TH-1002",
    sessionDate: "2026-09-30T13:00:00",
    durationMinutes: 60,
    sessionType: "individual",
    status: "scheduled",
    mode: "telehealth",
    paymentMethod: "online",
    followUpRequired: false,
    createdAt: "2026-09-29T10:00:00",
    updatedAt: "2026-09-29T10:00:00",
  },
];